backend:
  name: git-gateway
  branch: master

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Gallery Uploads
collections:
  - name: "gallery"
    label: "Gallery"
    folder: "/public/gallery"
    create: true
    slug: "{{year}}{{month}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish", name: "date", widget: "date"}
      - {label: "Categories", name: "categories", widget: "hidden", default: "Kitty"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Artwork", name: "galleryImage", widget: "image", required: true}

# Store Uploads
  - name: "store"
    label: "Store"
    folder: "/public/store"
    create: true
    slug: "{{year}}{{month}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish", name: "date", widget: "date"}
      - {label: "Categories", name: "categories", widget: "hidden", default: "Kitty"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Artwork", name: "galleryImage", widget: "image", required: true}
      - label: "Price"
        name: "price"
        widget: "object"
        fields:
          - {label: "4x6", name: "small", widget: "number", valueType: "float"}
          - {label: "5x7", name: "medium", widget: "number", valueType: "float"}
          - {label: "8x10", name: "large", widget: "number", valueType: "float"}