# Publish mode - Add 'confirmation' step
publish_mode: editorial_workflow

# CMS Type - Github | commit branch
backend:
  name: git-gateway
  branch: master

# Folder Locations
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# URL and Logo - Prod
# site_url: https://blaillustrations.netlify.com
# display_url: https://blaillustrations.netlify.com
# logo_url: https://blaillustrations.netlify.com/icons/16bitCharlie.svg

# URL and Logo - Netlify-domain
site_url: https://blaillustrations.netlify.com
display_url: https://blaillustrations.netlify.com
logo_url: https://blaillustrations.netlify.com/icons/16bitCharlie.svg

# Gallery Uploads
collections:
  - name: "gallery"
    label: "Gallery Item"
    folder: "/public/gallery"
    create: true
    slug: "{{year}}{{month}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish", name: "date", widget: "date"}
      - {label: "Categories", name: "categories", widget: "hidden", default: "galleryItem"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Artwork", name: "galleryImage", widget: "image", required: true}

# News (Artist Updates)
  - name: "news"
    label: "Main Page News"
    folder: "/public/news"
    create: true
    slug: "{{year}}{{month}}{{day}}--{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

# # Sticker Uploads
#   - name: "stickers"
#     label: "Sticker"
#     folder: "/public/stickers"
#     create: true
#     slug: "{{year}}{{month}}--{{slug}}"
#     fields:
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Publish", name: "date", widget: "date"}
#       - {label: "Categories", name: "categories", widget: "hidden", default: "stickerItem"}
#       - {label: "Tags", name: "tags", widget: "list", required: false}
#       - {label: "Artwork", name: "galleryImage", widget: "image", required: true}

# # Prints
#   - name: "prints"
#     label: "Prints"
#     folder: "/public/prints"
#     create: true
#     slug: "{{year}}{{month}}--{{slug}}"
#     fields:
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Publish", name: "date", widget: "date"}
#       - {label: "Categories", name: "categories", widget: "hidden", default: "printItem"}
#       - {label: "Tags", name: "tags", widget: "list", required: false}
#       - {label: "Artwork", name: "galleryImage", widget: "image", required: true}

# # Portrait Uploads
#   - name: "portraits"
#     label: "Portrait"
#     folder: "/public/portraits"
#     create: true
#     slug: "{{year}}{{month}}--{{slug}}"
#     fields:
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Publish", name: "date", widget: "date"}
#       - {label: "Categories", name: "categories", widget: "hidden", default: "portraitItem"}
#       - {label: "Tags", name: "tags", widget: "list", required: false}
#       - {label: "Artwork", name: "galleryImage", widget: "image", required: true}

# # Coloring Book Uploads
#   - name: "coloringBook"
#     label: "Coloring Book"
#     folder: "/public/coloring-books"
#     create: true
#     slug: "{{year}}{{month}}--{{slug}}"
#     fields:
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Download Link (url)", name: "downloadUrl", widget: "string", pattern: ['^https?', 'Should start with "http" or "https"']}


# Store Uploads
  # - name: "store"
  #   label: "Store"
  #   folder: "/public/store"
  #   create: true
  #   slug: "{{year}}{{month}}-{{slug}}"
  #   fields:
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish", name: "date", widget: "date"}
  #     - {label: "Categories", name: "categories", widget: "hidden", default: "Kitty"}
  #     - {label: "Tags", name: "tags", widget: "list", required: false}
  #     - {label: "Artwork", name: "galleryImage", widget: "image", required: true}
  #     - label: "Price"
  #       name: "price"
  #       widget: "object"
  #       fields:
  #         - {label: "4x6", name: "small", widget: "number", valueType: "float"}
  #         - {label: "5x7", name: "medium", widget: "number", valueType: "float"}
  #         - {label: "8x10", name: "large", widget: "number", valueType: "float"}

